### ISSUE TITLE
[PE-D][Tester D] Long names cannot be seen fully

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-1/tp#110]
![image.png](https://raw.githubusercontent.com/sanjevi13/ped/main/files/92e8d268-1737-403c-b3ef-25dcf6851614.png)

Extremely long names are replaced with the 3 dots, though it is unlikely that you will find such long names. 

When the window is minimised, some of the shorter names are cropped too, as seen below. This is not really a big issue though.

![image.png](https://raw.githubusercontent.com/sanjevi13/ped/main/files/2e6a2753-aa6e-462a-a2ba-e8785aecb3bc.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sanjevi13/ped#1

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/229272692-0b5d938b-4fe1-4f65-bf9b-e6250f05912c.png)

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/230000892-b2325f91-d4b5-416d-a90b-85c7007de8e8.png)
To be fixed through `planned features` in `DG`
Likely same implementation as #112 , #121
