### ISSUE TITLE
[PE-D][Tester D] Long addresses cannot be seen fully

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-1/tp#112]
Similar to the long names issue, minor issue.

![image.png](https://raw.githubusercontent.com/sanjevi13/ped/main/files/e7d2ba84-bf56-4f91-9483-8fcb45d77b21.png)

As you can see, long addresses are shortened and replaced with 3 dots, although unlikely that addresses will be that long.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sanjevi13/ped#2

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/229272553-67af8140-afc5-4434-937a-33bd46f41507.png)

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/230000636-b2d1cf9d-1f85-4eb3-ac99-5ccc6df00577.png)

Fix by implementation in `planned features` in `DG`
