### ISSUE TITLE
[PE-D][Tester C] Long tags do not wrap

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-1/tp#121]
Long text in tags do not wrap properly and any other tag that comes after it will not be visible either

![image.png](https://raw.githubusercontent.com/Sheemo/ped/main/files/25b0775b-7882-448a-b762-8192a3c7450a.png)

Commands used:

1. add n/Long Things Lover t/I love long tags This is a long tag I want to be able to see my long tag Please help me see it thank you very much
2. add n/I have a very very very long name my parents gave it to me when I was 7 years old when they decided that my name should be more than 100 characters long to mess with optical answer sheets
3. create tn/MusicTeam2 td/I want 2 music teams!!!
4. edit 2 T/MusicTeam2

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Sheemo/ped#2

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/229272196-3efb8583-e3c4-4339-b460-484d5f5d62e0.png)

**Comment by WillCWX** [comment]
![image](https://user-images.githubusercontent.com/55905659/229999636-51263978-d563-4817-8994-325a2471f405.png)

Fix this issue by using `planned future features`

**Comment by ChickenChiang** [comment]
# Include the following in UG: 
- Will include in future features to make tags of more than 15 characters to end with "...".
e.g. `t/PostGreStructuredQueryLanguage` will be displayed as "PostGreStructure...".
- Mention in the UG under tags that the tags are meant to be succinct, and we strongly recommend users to restrict the length of their tags to have a better user experience.
