### ISSUE TITLE
[PE-D][Tester B] UI size too small will cut the team list display

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-1/tp#137]
![sie.png](https://raw.githubusercontent.com/QQH0828/ped/main/files/ce0e74d8-1a69-40d1-a736-130b934671de.png)

When I was trying to resize the application, it worked fine, but if the width is small than some size, the team list will be cut off, maybe can add a horizontal scrollbar in the team list panel, so the reader can still see the team list display.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: QQH0828/ped#9

**Comment by ChickenChiang** [comment]
Will implement fix such that:
- TeamList is not cut off 
- Main Window cannot be resized smaller than what is useable
