### ISSUE TITLE
Abstract UG diagrams 

### ISSUE THREAD

**Issue by ChickenChiang** [AY2223S2-CS2103T-T17-1/tp#163]
# Change UG diagrams to not be over congested 
The following class diagram might have too many details, which might make it harder for Developers
![image](https://user-images.githubusercontent.com/96032660/230761024-42342aa5-efc1-4bb0-ad86-341a6ae1222b.png)

Might be confusing to developers since the both `Team` and `Person` has a reference to a `Name` class, which might lead readers to assum that they are the same instance when in fact they are not.

**Comment by chen-jerry-junior** [comment]
Finished
